---
- name: Start app container.
  containers.podman.podman_container:
    pod: "{{ pod_name }}"
    name: "{{ pod_name }}-app"
    image: "{{ image_name_nextcloud }}"
    state: started
    detach: true
    restart_policy: "on-failure"
    volumes:
      - "{{ volumes.app }}:/var/www/html:Z"
      - "{{ volumes.config }}:/var/www/html/config:Z"
      - "{{ volumes.data }}:/var/www/html/data:Z"
    env:
      MYSQL_HOST: 127.0.0.1
      MYSQL_USER: "{{ MYSQL_USER }}"
      MYSQL_DATABASE: "{{ MYSQL_DATABASE }}"
      MYSQL_PASSWORD: "{{ MYSQL_PASSWORD }}"
      NEXTCLOUD_ADMIN_USER: "{{ NEXTCLOUD_ADMIN_USER }}"
      NEXTCLOUD_ADMIN_PASSWORD: "{{ NEXTCLOUD_ADMIN_PASSWORD }}"
      NEXTCLOUD_TRUSTED_DOMAINS: "{{ NEXTCLOUD_TRUSTED_DOMAINS }}"
      OVERWRITEPROTOCOL: "{{ NEXTCLOUD_OVERWRITEPROTOCOL }}"
      OVERWRITECLIURL: "{{ NEXTCLOUD_OVERWRITECLIURL }}"
