---
- name: Ensure db container exists.
  containers.podman.podman_container:
    pod: "{{ pod_name }}"
    name: "{{ pod_name }}-db"
    image: "{{ image_name_mariadb }}"
    state: created
    detach: true
    restart_policy: "on-failure"
    volumes:
      - "{{ volumes.db }}:/var/lib/mysql:Z"
    env:
      MYSQL_USER: "{{ MYSQL_USER }}"
      MYSQL_DATABASE: "{{ MYSQL_DATABASE }}"
      MYSQL_PASSWORD: "{{ MYSQL_PASSWORD }}"
      MYSQL_ROOT_PASSWORD: "{{ MYSQL_ROOT_PASSWORD }}"
  # notify: Wait to initialized db.

- name: Flush handlers.
  ansible.builtin.meta: flush_handlers
