---
- name: Ensure podman is installed.
  ansible.builtin.dnf:
    name: podman
    state: present
  become: true

- name: Create volume directories with correct ownership.
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    mode: "{{ item.mode }}"
    state: directory
  loop:
    - { path: "{{ volumes.db }}", owner: "100998", mode: "0755"}
    - { path: "{{ volumes.app }}", owner: "100032", mode: "755"}
    - { path: "{{ volumes.config }}", owner: "100032", mode: "755"}
    - { path: "{{ volumes.data }}", owner: "100032", mode: "770"}
  become: true

- name: Start nextcloud pod.
  containers.podman.podman_pod:
    name: "{{ pod_name }}"
    state: started
    publish: "{{ pod_http_port }}:80"

- name: Import db container tasks.
  ansible.builtin.import_tasks: db.yml

- name: Import app container tasks.
  ansible.builtin.import_tasks: app.yml

- name: Import nginx proxy tasks.
  ansible.builtin.import_tasks: nginx.yml
