---
- name: Ensure podman is installed.
  ansible.builtin.dnf:
    name: podman
    state: present
  become: true

- name: Create volume directories.
  ansible.builtin.file:
    path: "{{ item.value }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0755"
    state: directory
  loop: "{{ volumes | dict2items }}"
  become: true

- name: Fix permission on nextcloud volumes.
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "100032"
    group: "100032"
    mode: "0755"
  loop:
    - "{{ volumes.app }}"
    - "{{ volumes.config }}"
    - "{{ volumes.data }}"
  become: true

- name: Start nextcloud pod.
  containers.podman.podman_pod:
    name: nc
    state: started
    publish: "{{ port }}:80"
  register: pod

- name: Debug
  ansible.builtin.debug:
    var: pod

- name: Import db container tasks.
  ansible.builtin.import_tasks: db.yml

- name: Import app container tasks.
  ansible.builtin.import_tasks: app.yml

- name: Import nginx proxy tasks.
  ansible.builtin.import_tasks: nginx.yml

## TODO
#  SELinux
