---
- name: Ensure podman is installed.
  ansible.builtin.dnf:
    name: podman
    state: present
  become: true

- name: Create volume directories.
  ansible.builtin.file:
    path: "{{ item.value }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0755"
    state: directory
  loop: "{{ volumes | dict2items }}"
  become: true

- name: Start nextcloud pod.
  containers.podman.podman_pod:
    name: nc
    state: started
    publish: "8080:80"
  register: pod

- name: Debug
  ansible.builtin.debug:
    var: pod

- name: Start db container.
  containers.podman.podman_container:
    pod: nc
    name: nextcloud-db
    image: docker.io/library/mariadb
    state: started
    detach: true
    restart_policy: "on-failure"
    volumes:
      - "{{ volumes.db }}:/var/lib/mysql:Z"
    env:
      MYSQL_USER: nextcloud
      MYSQL_DATABASE: nextcloud
      MYSQL_PASSWORD: nextcloud
      MYSQL_ROOT_PASSWORD: nextcloud
  notify: Wait to initialized db.

- name: Flush handlers.
  ansible.builtin.meta: flush_handlers

- name: Start app container.
  containers.podman.podman_container:
    pod: nc
    name: nextcloud-app
    image: docker.io/library/nextcloud:latest
    state: started
    detach: true
    restart_policy: "on-failure"
    volumes:
      - "{{ volumes.app }}:/var/www/html:Z"
      - "{{ volumes.config }}:/var/www/html/config:Z"
      - "{{ volumes.data }}:/var/www/html/data:Z"
    env:
      MYSQL_HOST: 127.0.0.1
      MYSQL_USER: nextcloud
      MYSQL_DATABASE: nextcloud
      MYSQL_PASSWORD: nextcloud
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: nextcloud
