---
- name: Ensure podman is installed.
  ansible.builtin.dnf:
    name: podman
    state: present
  become: true

- name: Create volume directories with correct ownership.
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    mode: "0755"
    state: directory
  loop:
    - { path: "{{ volumes.db }}", owner: "{{ ansible_user_id }}"}
    - { path: "{{ volumes.app }}", owner: "100032"}
    - { path: "{{ volumes.config }}", owner: "100032"}
    - { path: "{{ volumes.data }}", owner: "100032"}
  become: true

- name: Start nextcloud pod.
  containers.podman.podman_pod:
    name: nc
    state: started
    publish: "{{ port }}:80"

- name: Import db container tasks.
  ansible.builtin.import_tasks: db.yml

- name: Import app container tasks.
  ansible.builtin.import_tasks: app.yml

- name: Import nginx proxy tasks.
  ansible.builtin.import_tasks: nginx.yml
