---
- name: Ensure nginx is installed.
  become: true
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Ensure nginx is enabled and started.
  become: true
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Ensure nginx proxy can connect to network.
  become: true
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true

- name: Ensure firewall is running.
  become: true
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Ensure http services are allowed.
  become: true
  ansible.posix.firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  loop:
    - http
    - https

- name: Generate SSL certificates with tailscale.
  become: true
  ansible.builtin.command:
    cmd: >
      tailscale cert
      --cert-file /etc/nginx/{{ pod_name }}.crt
      --key-file /etc/nginx/{{ pod_name }}.key
      {{ server_name }}
    creates: "/etc/nginx/{{ pod_name }}.*"
  notify: Restart nginx.

- name: Copy configuration template.
  become: true
  ansible.builtin.template:
    src: templates/tailnet.nginx.conf.j2
    dest: /etc/nginx/conf.d/{{ pod_name }}.conf
    mode: "0644"
  notify: Restart nginx.

- name: Flush handlers.
  ansible.builtin.meta: flush_handlers
