---
- name: Converge
  hosts: all

  roles:
    - tailscale

  tasks:
    - name: "Include palekiwi.nextcloud"
      ansible.builtin.include_role:
        name: "palekiwi.nextcloud"

    - name: Wait for server to finish setup.
      ansible.builtin.wait_for:
        timeout: 5

    - name: Test server response.
      ansible.builtin.uri:
        url: "https://{{ inventory_hostname_short }}.paradise-liberty.ts.net"
        return_content: true
        status_code: 200
      register: response
      failed_when: "'login' not in response.content"

    - name: Print machine IP address.
      ansible.builtin.debug:
        var: ansible_host
